// 등록된 교재 목록 — 마케팅 사이트의 교재 카탈로그(src/data/textbookCatalog.ts)에서
// 이름만 옮겨온 단순 목록이다. 별도 Textbook 모델 없이 문자열로만 저장하므로
// (Enrollment.textbookName), 새 교재가 생기면 아래 RAW_TEXTBOOK_OPTIONS에 추가하면 된다.
// "Free Talking"은 정규 교재 없이 자유 대화로 진행하는 수업을 위한 항목이다.

// "Exploring English 1-6"처럼 권수 범위로 뭉뚱그려진 이름을, 드롭다운에서는
// "Exploring English 1" ~ "Exploring English 6"처럼 한 권씩 고를 수 있게 펼친다.
// 이름에서 처음 나오는 숫자-숫자(- 또는 ~) 패턴만 대상으로 하므로 "1000 Useful
// Words 2018"이나 "Time to Talk series Pre A1-B2"처럼 진짜 권수 범위가 아닌 숫자는
// 건드리지 않는다. "Situation English 1~60"처럼 권수가 지나치게 많은 시리즈는 한
// 권씩 고르는 게 오히려 비현실적이라 원래 표기 그대로 둔다(MAX_EXPAND_VOLUMES).
const MAX_EXPAND_VOLUMES = 20;
const VOLUME_RANGE_PATTERN = /(\d+)[-~](\d+)/;

function expandVolumeRange(name: string): string[] {
  const match = VOLUME_RANGE_PATTERN.exec(name);
  if (!match || match.index == null) return [name];
  const start = Number(match[1]);
  const end = Number(match[2]);
  if (!(start < end) || end - start + 1 > MAX_EXPAND_VOLUMES) return [name];

  const before = name.slice(0, match.index);
  const after = name.slice(match.index + match[0].length);
  const volumes: string[] = [];
  for (let n = start; n <= end; n++) {
    volumes.push(`${before}${n}${after}`);
  }
  return volumes;
}

const RAW_TEXTBOOK_OPTIONS: string[] = [
  "Free Talking",
  "100 Interactive English Lessons",
  "100-pattern-English",
  "1000 Useful Words 2018",
  "2000 Core English Words 1-4",
  "4000 Essential English Words",
  "50 Debate Prompts Kids",
  "50 Question English Basics",
  "500 Real English Phrases",
  "A Little Prince",
  "Active English Discussion",
  "All in all books (?)",
  "American Headway 1-3",
  "American School Textbook (core/basic/easy/preschool)",
  "Animal Farm (George Orwell)",
  "Backpack 1-6 (구판+신판)",
  "Baisic Survival for Trip",
  "Basic English Grammar",
  "Big English 1-3 SB (American)",
  "Big English 1-5 SB (British)",
  "Bricks Reading",
  "Cambridge English for Job Hunting",
  "Can You Believe It 1-4",
  "Chat Room for Teens 1-3",
  "Close Reader 1-2",
  "Core Pattern 233",
  "Daily English",
  "Debate Pro Junior Book 1-4",
  "Debating Challenge 1-3",
  "Disney Learning Series",
  "Easy English with Games 1-3",
  "Easy Link 1-5",
  "English Code 1-4 Grammar Book",
  "English File 4th Edition",
  "English Grammar for the Utterly Confused",
  "Everybody Up 1-6 2nd",
  "Everyday English",
  "Everyone Speak Kids 1-3",
  "Exploring English 1-6",
  "Exploring Reading Easy 1-2",
  "Exploring Reading Very Easy 1-3",
  "Express Yourself 1-2",
  "Family and Friends 1-6 2nd Edition",
  "First Step in Reading 1-2",
  "Fly High, Fly Guy!",
  "Frog and Toad Are Friends",
  "Fun With Language Book 1-6",
  "General English (?)",
  "Get Ready for First Grade Workbook",
  "Getting the Message 1-3",
  "Global Favorite Book01 (미국교과서 리딩 AST basic1)",
  "Global News",
  "Grammar Ebook Level 1",
  "Grammar Ebook Level 2",
  "Grammar Friends",
  "Grammar Genius",
  "Grammar in Use",
  "Guided Writing Plus 1",
  "Hand in Hand 1-6, Starter",
  "Hang Out 1-6",
  "Henry and Mudge (전권 zip)",
  "Henry and Mudge (폴더)",
  "Hip Hip Hooray 1-6",
  "Impact Values",
  "Insight Link",
  "Interchange 1-2",
  "Jazz English (?)",
  "Judy Moody was in a Mood",
  "Junior Debate Club 1-2 (3권 누락)",
  "Kid's Box Activity Book 1-3",
  "Let's Go",
  "Let's Go Phonics",
  "Let's Talk",
  "Lord of the Flies (William Golding)",
  "Matilda (Roald Dahl Original)",
  "My Best Reading 1-4",
  "My First English Discussion 1-2",
  "My First Series",
  "Nate the Great",
  "National Geographic Our World 2nd",
  "National Geographic Readers",
  "New Children's Talk",
  "New Grammar Time 1-3",
  "News Discussion",
  "Nonfiction Reading Practice Grade 1-4",
  "Open to Debate",
  "Oxford Bright Ideas Class Book 1-5",
  "Oxford Discover 1-6",
  "Oxford Discover Grammar 1-6",
  "Oxford Phonics World 1-5",
  "Oxford Primary Skills 1-6 Reading and Writing",
  "Oxford Reading Tree",
  "Performance Assessment 1-2",
  "Phonics Party",
  "Pre-Inter-Advanced Conversation",
  "Primary Longman-Express",
  "Progressive Phonics 1-5",
  "Read and Understand 1-4",
  "Reading Adventures 1-3",
  "Reading Challenge 1-3",
  "Reading Expert 1-4 (5권 누락)",
  "Reading Explorer Foundation-5",
  "Reading for the Real World 1-3 4th Ed",
  "Reading Future Discover 1-3",
  "Reading Key Preschool 1~6",
  "Reading Rocket 1-3",
  "Reading Sketch Up 1-3",
  "Reading Sponge 1-3",
  "Reading Starter 1-3",
  "Reading Wise 1-3",
  "Side by Side 1-4",
  "Situation English 1~60",
  "Smart Grammar and Vocabulary",
  "Smart Grammar and Vocabulary 1a,1b,2a",
  "Smart Phonics 1-5",
  "Sounds Great 1-5",
  "Spark Times",
  "Speak Your Mind 1-2",
  "Speaking for Speeches 1-3",
  "Speaking Pro 1-2",
  "Speech Contest 1-3",
  "Speech Like Me 1-4",
  "Story Books",
  "Subject Link 1-5",
  "Super Minds Super Grammar Practice Book",
  "Super Star Book 1-6",
  "SuperKids Student Book 1-4",
  "Talk Talk Talk",
  "Talk Time 1-3",
  "Talking Talking! for Junior 1-2",
  "Teen 2 Teen 1-4",
  "Teen Talk 1-2",
  "The Express Picture Dictionary SB",
  "The Giver (Lois Lowry)",
  "The Hunger Games (Book 1)",
  "The Maze Runner (Book 1)",
  "Time to Talk series Pre A1-B2",
  "To Kill a Mockingbird (Harper Lee)",
  "Totally True 1-2",
  "Touchstone 1-4",
  "Travel English",
  "True Stories",
  "Unlock Reading and Writing 1-4",
  "Unlock Reading, Writing and Critical Thinking",
  "Vocabulary in Use 4th Edition",
  "Vocabulary Workshop Series",
  "What a World 1-3",
  "What Do You Think 1-2",
  "Wonderland Junior A, B",
  "WonderSkills Reading",
  "Wordly Wise 1-12 4th Edition",
  "World English - TED Talks",
  "World Wonders 1-2",
  "영어회화 100일",
];

export const TEXTBOOK_OPTIONS: string[] = RAW_TEXTBOOK_OPTIONS.flatMap(expandVolumeRange);
